# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: ActionScript 3 CI

# Github worflows do not support actionscript directly.
# However the build uses ant, which is usually used to build java projects.
# The ant task (mxmlc) provided by the flex SDK (ant/lib/flexTasks.jar) is used to build the project.

on:
  push:
    # Just so the CI won't complain about Vanilla+ failing, since V+ isn't configured for CI.
    branches-ignore: [ master ]
  pull_request:
    branches: [ master-wip ]

env:
  # tell the build file where to find the flex SDK
  FLEX_HOME: "build-dep/bin/flex/"
  # this is to trick the flash player into thinking it is running on a desktop
  DISPLAY: ":1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      #- name: Download and install Android SDK
      #  uses: android-actions/setup-android@v3

      - name: Install Flex SDK
        uses: joshtynjala/setup-apache-flex-action@v2
        with:
          flex-version: "4.16.1"
          air-version: "33.1.1.935"
          accept-air-license: true

      # install VNC and xfce4 so we have a desktop, as the flash player requires one:
      - name: Install desktop
        run: sudo apt install tightvncserver xfce4 ant ant-optional aapt -y

      # start a VNC session, this will be the desktop for tests
      - name: Start VNC
        run: Xvnc :1 &

      # this is where the build happens. A separate build is started for every entry in the matrix element
      - name: Build
        run: ant allCI

      - name: Save Debug SWF
        uses: actions/upload-artifact@v3
        with:
          name: debug-swf
          path: target/CoC-debug.swf

      - name: Save Release SWF
        uses: actions/upload-artifact@v3
        with:
          name: release-swf
          path: target/CoC-release.swf

      - name: Save Android armv7 APK
        uses: actions/upload-artifact@v3
        with:
          name: mobile-arm7-32bit-apk
          path: target/CoC-Mobile-armv7.apk

      - name: Save Android armv8 APK
        uses: actions/upload-artifact@v3
        with:
          name: mobile-arm8-64bit-apk
          path: target/CoC-Mobile-armv8.apk

      # discord notifier to tell us if build succeeded or failed, and the link to download the artifacts.
      - name: Discord notification to channel
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
        continue-on-error: true

      - name: Cat-ing ant area
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: aapt-bin
          path: /usr/local/bin/ApacheFlexSDK/apache-flex-sdk-4.16.1-bin/lib/android/bin/aapt